### ISSUE TITLE
make it possible to echo messages to stdout or stderr

### ISSUE THREAD

**Issue by stylewarning** [jobec/rfc5424-logging-handler#27]
Using this logging facility, it's not possible to get the formatted messages to stdout. This is useful if you're debugging, or can't easily inspect the receiving syslog endpoint.

**Comment by jobec** [comment]
I feel a bit mixed about this.

1. You can just as well hook up a debugger to get this functionality, because it's not something you'll ever need while running "live".

1. This defeats goal of python's logging features.

If any, I would rather implement it as a debug "flag" rather than an "echo to stream", making it much more clear that it is for debugging this package, rather then using it to bypass setting up other log handlers.

**Comment by stylewarning** [comment]
> I feel a bit mixed about this.
> 
>     1. You can just as well hook up a debugger to get this functionality, because it's not something you'll ever need while running "live".
> 
>     2. This defeats goal of python's logging features.
> 
> 
> If any, I would rather implement it as a debug "flag" rather than an "echo to stream", making it much more clear that it is for debugging this package, rather then using it to bypass setting up other log handlers.

This is not true. Our use-case is to have log messages go to stdout in a Docker container, where in our default configuration log messages are collected. (The docker containers don't even have a syslog running.)

**Comment by jobec** [comment]
docker does capture stderr: https://docs.docker.com/config/containers/logging/

Just for clarification:  
Are you trying to debug this package or a system that is supposed to receive the syslog messages?  
Or do you want the format of the logs it produces on cli?

**Comment by stylewarning** [comment]
For clarification, we are looking to capture logs, by having application programmers log their services to stdout, having devops deploy the docker images, and configuring data sent to stdout to be captured by rsyslog, which forwards over TCP to a log service like Splunk.

Being able to see the messages is a nice bonus, but isn’t the critical bit.

**Comment by jobec** [comment]
Ok, that makes sense. And indeed, RFC5424 is about the format, not the transport mechanism.

From this point of view, sending to stdout/stderr/... would build upon not tightly coupling the transport mechanism with the formatting of the message. Hence, this should be implemented as a means of configuring the transport/destination in an extra way. Not as sending the message in 2 directions.

This does mean a bit more work, because some basic things in the package built upon what's in python's default syslog handler (like the socket creation). All that should actually be pulled into this package to allow it to do different things based upon whatever is configured as the transport/destination. Because the default sysloghandler is specifically [ focused on UDP/TCP/socket transport](https://github.com/python/cpython/blob/master/Lib/logging/handlers.py#L795) and doesn't support other things.

**Comment by stylewarning** [comment]
I’ll track and take a look!

**Comment by stylewarning** [comment]
@jobec We tested this in our stack, and it works great!

**Comment by jobec** [comment]
Excellent. I'll need some more work on the tests. But if you want, I can release it as an alpha version already.

**Comment by stylewarning** [comment]
That would be awesome!

**Comment by jobec** [comment]
I just went with a new minor release straight away :-)

Enjoy 1.4.0 => https://pypi.org/project/rfc5424-logging-handler/
